// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKcmtZ-Zwtg25TiL9UQUDL7kFrArLTIc0',
    appId: '1:290132275309:web:729c88d227435b5ea48f64',
    messagingSenderId: '290132275309',
    projectId: 'skripsicb1',
    authDomain: 'skripsicb1.firebaseapp.com',
    storageBucket: 'skripsicb1.appspot.com',
    measurementId: 'G-V0LRFML6RE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnRZ5hX4UNSlZNvFLoAWQ61hQ8FNpQdjQ',
    appId: '1:290132275309:android:026820b51b66d8faa48f64',
    messagingSenderId: '290132275309',
    projectId: 'skripsicb1',
    storageBucket: 'skripsicb1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYUAXxVDkp2TvczJTb9y_Sy9-zA-wrKuk',
    appId: '1:290132275309:ios:92169eb41232f2aaa48f64',
    messagingSenderId: '290132275309',
    projectId: 'skripsicb1',
    storageBucket: 'skripsicb1.appspot.com',
    androidClientId: '290132275309-7bu4oodqmbvpdmvchf7b40vkamohkr8l.apps.googleusercontent.com',
    iosClientId: '290132275309-cf5bmlv2ndcn1or78ejhu9mackagso6p.apps.googleusercontent.com',
    iosBundleId: 'com.example.cekGrammerPlagiat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYUAXxVDkp2TvczJTb9y_Sy9-zA-wrKuk',
    appId: '1:290132275309:ios:92169eb41232f2aaa48f64',
    messagingSenderId: '290132275309',
    projectId: 'skripsicb1',
    storageBucket: 'skripsicb1.appspot.com',
    androidClientId: '290132275309-7bu4oodqmbvpdmvchf7b40vkamohkr8l.apps.googleusercontent.com',
    iosClientId: '290132275309-cf5bmlv2ndcn1or78ejhu9mackagso6p.apps.googleusercontent.com',
    iosBundleId: 'com.example.cekGrammerPlagiat',
  );
}
